import {useEffect,useMemo,useState} from 'react';
import {Activity,AlertTriangle,CalendarDays,Files,Repeat2} from 'lucide-react';
import {supabase} from '../lib/supabase';

type Daily={metric_date:string;movements:number;reconciled:number;open:number;missing_native_idtr:number;amount:number};
type ChartScale='auto'|'daily'|'weekly'|'monthly'|'yearly';
type ImportRow={id:string;original_filename:string;state:string;source_rows:number;inserted_rows:number;duplicate_rows:number;rejected_rows:number;period_start:string|null;period_end:string|null;created_at:string;completed_at:string|null;stage:string;error_message:string|null};
const path=(points:readonly (readonly [number,number])[])=>points.length?points.slice(1).reduce((value,[x,y],index)=>{const [px,py]=points[index],middle=(px+x)/2;return `${value} C ${middle} ${py}, ${middle} ${y}, ${x} ${y}`;},`M ${points[0][0]} ${points[0][1]}`):'';
const calendarDays=(items:Daily[])=>{if(!items.length)return[];const byDate=new Map(items.map(item=>[item.metric_date,item])),start=new Date(`${items[0].metric_date}T00:00:00Z`),end=new Date(`${items[items.length-1].metric_date}T00:00:00Z`),result:{date:string;item:Daily|null;weekend:boolean;label:string}[]=[];for(const cursor=new Date(start);cursor<=end;cursor.setUTCDate(cursor.getUTCDate()+1)){const date=cursor.toISOString().slice(0,10),weekend=[0,6].includes(cursor.getUTCDay());result.push({date,item:weekend?null:byDate.get(date)??null,weekend,label:weekend?'FDS':date.slice(5)});}return result.filter((day,index,days)=>!day.weekend||index===0||!days[index-1].weekend);};
const segmentedPaths=(values:(number|null)[],max:number,width=800,height=170)=>{const segments:(readonly [number,number])[][]=[];let segment:[number,number][]=[];values.forEach((value,index)=>{if(value===null){if(segment.length)segments.push(segment);segment=[];return;}const x=values.length===1?width/2:index*(width/(values.length-1)),y=height-(value/Math.max(1,max))*height;segment.push([x,y]);});if(segment.length)segments.push(segment);return segments;};
const automaticScale=(days:number):Exclude<ChartScale,'auto'>=>days<=45?'daily':days<=240?'weekly':days<=1095?'monthly':'yearly';
const aggregateDaily=(items:Daily[],scale:Exclude<ChartScale,'auto'>)=>{if(scale==='daily')return items;const grouped=new Map<string,Daily>();for(const item of items){const date=new Date(`${item.metric_date}T00:00:00Z`);let key:string;if(scale==='weekly'){const day=date.getUTCDay()||7;date.setUTCDate(date.getUTCDate()-day+1);key=date.toISOString().slice(0,10);}else if(scale==='monthly')key=`${item.metric_date.slice(0,7)}-01`;else key=`${item.metric_date.slice(0,4)}-01-01`;const before=grouped.get(key)??{metric_date:key,movements:0,reconciled:0,open:0,missing_native_idtr:0,amount:0};before.movements+=item.movements;before.reconciled+=item.reconciled;before.open+=item.open;before.missing_native_idtr+=item.missing_native_idtr;before.amount+=Number(item.amount);grouped.set(key,before);}return [...grouped.values()].sort((a,b)=>a.metric_date.localeCompare(b.metric_date));};

export default function V2History({revision=0}:{revision?:number}){
  const [daily,setDaily]=useState<Daily[]>([]),[imports,setImports]=useState<ImportRow[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[scale,setScale]=useState<ChartScale>('auto');
  useEffect(()=>{let active=true;void (async()=>{try{
    const series=await supabase.from('rt_v2_series').select('id').order('created_at',{ascending:true}).limit(1).maybeSingle();if(series.error)throw series.error;if(!series.data)return;
    const [metrics,history]=await Promise.all([
      supabase.from('rt_v2_daily_metrics').select('metric_date,movements,reconciled,open,missing_native_idtr,amount').eq('series_id',series.data.id).order('metric_date',{ascending:true}),
      supabase.from('rt_v2_imports').select('id,original_filename,state,source_rows,inserted_rows,duplicate_rows,rejected_rows,period_start,period_end,created_at,completed_at,stage,error_message').eq('series_id',series.data.id).order('period_start',{ascending:false,nullsFirst:false}).order('period_end',{ascending:false,nullsFirst:false}).order('created_at',{ascending:true}),
    ]);if(metrics.error)throw metrics.error;if(history.error)throw history.error;if(active){setDaily((metrics.data??[]) as Daily[]);setImports((history.data??[]) as ImportRow[]);}
  }catch(cause){if(active)setError(cause instanceof Error?cause.message:'Não foi possível carregar o histórico V2.');}finally{if(active)setLoading(false);}})();return()=>{active=false};},[revision]);
  const summary=useMemo(()=>({movements:daily.reduce((sum,item)=>sum+item.movements,0),reconciled:daily.reduce((sum,item)=>sum+item.reconciled,0),open:daily.reduce((sum,item)=>sum+item.open,0),withoutIdtr:daily.reduce((sum,item)=>sum+item.missing_native_idtr,0)}),[daily]);
  const effectiveScale=scale==='auto'?automaticScale(daily.length):scale,chartData=useMemo(()=>aggregateDaily(daily,effectiveScale),[daily,effectiveScale]);
  const calendar=useMemo(()=>effectiveScale==='daily'?calendarDays(chartData):chartData.map(item=>({date:item.metric_date,item,weekend:false,label:effectiveScale==='weekly'?`S ${item.metric_date.slice(5)}`:effectiveScale==='monthly'?item.metric_date.slice(0,7):item.metric_date.slice(0,4)})),[chartData,effectiveScale]);
  if(loading)return <section className="central-loading" role="status"><div className="processing-spinner"><i/><i/><i/></div><div><p className="eyebrow">HISTÓRICO</p><h2>A carregar a série diária</h2></div></section>;
  if(error)return <section className="panel empty-state"><AlertTriangle size={28}/><h2>Não foi possível carregar o histórico</h2><p>{error}</p></section>;
  if(!daily.length&&!imports.length)return <section className="panel empty-state"><Files size={28}/><h2>Ainda não existem análises guardadas</h2><p>O primeiro extrato concluído iniciará a série diária.</p></section>;
  const chartWidth=scale==='daily'?Math.max(800,calendar.length*34):800,max=Math.max(1,...chartData.map(item=>item.movements)),totalSegments=segmentedPaths(calendar.map(day=>day.item?.movements??null),max,chartWidth),reconciledSegments=segmentedPaths(calendar.map(day=>day.item?.reconciled??null),max,chartWidth),xStep=calendar.length>1?chartWidth/(calendar.length-1):0,labelStep=Math.max(1,Math.ceil(calendar.length/12));
  return <div className="history-page v2-history">
    <section className="history-kpis expanded"><article><CalendarDays/><span>Dias com dados</span><strong>{daily.length}</strong></article><article><Activity/><span>Total processado</span><strong>{summary.movements.toLocaleString('pt-AO')}</strong><small>{summary.withoutIdtr.toLocaleString('pt-AO')} sem IDTR ( /26)</small></article><article><Repeat2/><span>Reconciliados</span><strong>{summary.reconciled.toLocaleString('pt-AO')}</strong></article><article><AlertTriangle/><span>Pendentes</span><strong>{summary.open.toLocaleString('pt-AO')}</strong></article><article><Files/><span>Importações concluídas</span><strong>{imports.filter(item=>item.state==='completed').length}</strong><small>{imports.filter(item=>item.state==='failed').length} interrompidas</small></article></section>
    {daily.length>0&&<section className="history-chart panel smooth-chart"><div className="panel-head"><div><h2>Evolução {effectiveScale==='daily'?'diária':effectiveScale==='weekly'?'semanal':effectiveScale==='monthly'?'mensal':'anual'}</h2><p>{effectiveScale==='daily'?'Calendário corrido · fins de semana compactados · dias sem movimentos mantidos em branco':'Escala agregada automaticamente; pode escolher outra escala para análise detalhada.'}</p></div><label className="chart-scale">Escala<select value={scale} onChange={event=>setScale(event.target.value as ChartScale)}><option value="auto">Automática ({effectiveScale==='daily'?'diária':effectiveScale==='weekly'?'semanal':effectiveScale==='monthly'?'mensal':'anual'})</option><option value="daily">Diária</option><option value="weekly">Semanal</option><option value="monthly">Mensal</option><option value="yearly">Anual</option></select></label></div><div className="history-chart-scroll"><svg viewBox={`0 0 ${chartWidth} 210`} style={{width:chartWidth}} role="img" aria-label="Evolução V2 em calendário contínuo">{calendar.map((day,index)=>day.weekend?<line className="calendar-weekend" key={`w-${day.date}`} x1={index*xStep} x2={index*xStep} y1="8" y2="172"/>:null)}{effectiveScale==='daily'&&calendar.map((day,index)=>index>0&&day.date.slice(0,7)!==calendar[index-1].date.slice(0,7)?<line className="calendar-month" key={`month-${day.date}`} x1={index*xStep} x2={index*xStep} y1="0" y2="180"/>:null)}{calendar.map((day,index)=>!day.item&&!day.weekend?<line className="calendar-missing" key={`m-${day.date}`} x1={index*xStep} x2={index*xStep} y1="0" y2="180"/>:null)}{totalSegments.map((points,index)=><path className="total-line" key={`t-${index}`} d={path(points)}/>)}{reconciledSegments.map((points,index)=><path className="automatic-line" key={`r-${index}`} d={path(points)}/>)}{calendar.map((day,index)=>day.item?<circle className="daily-point" key={day.date} cx={calendar.length===1?chartWidth/2:index*xStep} cy={170-(day.item.movements/max)*170} r="3"/>:null)}{calendar.map((day,index)=>(day.weekend||index%labelStep===0||index===calendar.length-1)?<text className={day.weekend?'weekend-label':''} key={day.date} x={calendar.length===1?chartWidth/2:index*xStep} y="202" textAnchor={index===0?'start':index===calendar.length-1?'end':'middle'}>{day.label}</text>:null)}</svg></div><div className="history-legend"><span className="total">Total</span><span className="automatic">Reconciliados</span>{effectiveScale==='daily'&&<><span className="missing">Dia sem movimentos</span><span className="weekend">Fim de semana</span></>}</div></section>}
    <section className="panel"><div className="panel-head"><div><h2>Importações</h2><p>Cada ficheiro só fica concluído após leitura, reconciliação e cálculo dos indicadores.</p></div></div><div className="table-wrap"><table><thead><tr><th>Período contabilístico</th><th>Ficheiro</th><th>Lidos</th><th>Inseridos</th><th>Duplicados</th><th>Rejeitados</th><th>Concluído em</th><th>Estado</th></tr></thead><tbody>{imports.map(item=><tr key={item.id}><td>{item.period_start??'—'} a {item.period_end??'—'}</td><td>{item.original_filename}</td><td>{item.source_rows.toLocaleString('pt-AO')}</td><td>{item.inserted_rows.toLocaleString('pt-AO')}</td><td>{item.duplicate_rows.toLocaleString('pt-AO')}</td><td>{item.rejected_rows.toLocaleString('pt-AO')}</td><td>{new Intl.DateTimeFormat('pt-AO',{dateStyle:'short',timeStyle:'short'}).format(new Date(item.completed_at??item.created_at))}</td><td><span className={`badge ${item.state==='completed'?'automatic':'unreconciled'}`}>{item.state==='completed'?'Concluída':item.stage}</span>{item.error_message&&<small className="import-failure">{item.error_message}</small>}</td></tr>)}</tbody></table></div></section>
  </div>;
}
