import {useEffect,useMemo,useState} from 'react';
import {Activity,AlertTriangle,CalendarDays,CheckCircle2,Files} from 'lucide-react';
import {supabase} from '../lib/supabase';

type Daily={metric_date:string;movements:number;reconciled:number;open:number;missing_native_idtr:number;amount:number};
type ImportRow={id:string;original_filename:string;state:string;source_rows:number;inserted_rows:number;duplicate_rows:number;rejected_rows:number;period_start:string|null;period_end:string|null;created_at:string;completed_at:string|null;stage:string;error_message:string|null};
const coords=(values:number[],max:number,width=800,height=170)=>values.map((value,index)=>[values.length===1?width/2:index*(width/(values.length-1)),height-(value/Math.max(1,max))*height] as const);
const path=(points:readonly (readonly [number,number])[])=>points.length?points.slice(1).reduce((value,[x,y],index)=>{const [px,py]=points[index],middle=(px+x)/2;return `${value} C ${middle} ${py}, ${middle} ${y}, ${x} ${y}`;},`M ${points[0][0]} ${points[0][1]}`):'';

export default function V2History(){
  const [daily,setDaily]=useState<Daily[]>([]),[imports,setImports]=useState<ImportRow[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
  useEffect(()=>{let active=true;void (async()=>{try{
    const series=await supabase.from('rt_v2_series').select('id').order('created_at',{ascending:true}).limit(1).maybeSingle();if(series.error)throw series.error;if(!series.data)return;
    const [metrics,history]=await Promise.all([
      supabase.from('rt_v2_daily_metrics').select('metric_date,movements,reconciled,open,missing_native_idtr,amount').eq('series_id',series.data.id).order('metric_date',{ascending:true}),
      supabase.from('rt_v2_imports').select('id,original_filename,state,source_rows,inserted_rows,duplicate_rows,rejected_rows,period_start,period_end,created_at,completed_at,stage,error_message').eq('series_id',series.data.id).order('created_at',{ascending:false}),
    ]);if(metrics.error)throw metrics.error;if(history.error)throw history.error;if(active){setDaily((metrics.data??[]) as Daily[]);setImports((history.data??[]) as ImportRow[]);}
  }catch(cause){if(active)setError(cause instanceof Error?cause.message:'Não foi possível carregar o histórico V2.');}finally{if(active)setLoading(false);}})();return()=>{active=false};},[]);
  const summary=useMemo(()=>({movements:daily.reduce((sum,item)=>sum+item.movements,0),reconciled:daily.reduce((sum,item)=>sum+item.reconciled,0),open:daily.reduce((sum,item)=>sum+item.open,0)}),[daily]);
  if(loading)return <section className="central-loading" role="status"><div className="processing-spinner"><i/><i/><i/></div><div><p className="eyebrow">HISTÓRICO V2</p><h2>A carregar a série diária</h2></div></section>;
  if(error)return <section className="panel empty-state"><AlertTriangle size={28}/><h2>Não foi possível carregar o histórico</h2><p>{error}</p></section>;
  if(!daily.length&&!imports.length)return <section className="panel empty-state"><Files size={28}/><h2>Ainda não existem análises V2 guardadas</h2><p>O primeiro extrato concluído iniciará a série diária.</p></section>;
  const max=Math.max(1,...daily.map(item=>item.movements)),totalPoints=coords(daily.map(item=>item.movements),max),reconciledPoints=coords(daily.map(item=>item.reconciled),max);
  return <div className="history-page v2-history">
    <section className="history-kpis expanded"><article><CalendarDays/><span>Dias com dados</span><strong>{daily.length}</strong></article><article><Activity/><span>Total processado</span><strong>{summary.movements.toLocaleString('pt-AO')}</strong></article><article><CheckCircle2/><span>Reconciliados</span><strong>{summary.reconciled.toLocaleString('pt-AO')}</strong></article><article><AlertTriangle/><span>Pendentes</span><strong>{summary.open.toLocaleString('pt-AO')}</strong></article><article><Files/><span>Importações concluídas</span><strong>{imports.filter(item=>item.state==='completed').length}</strong><small>{imports.filter(item=>item.state==='failed').length} interrompidas</small></article></section>
    {daily.length>0&&<section className="history-chart panel smooth-chart"><div className="panel-head"><div><h2>Evolução diária</h2><p>Movimentos processados e reconciliados por período contabilístico</p></div></div><svg viewBox="0 0 800 210" role="img" aria-label="Evolução diária V2"><path className="total-line" d={path(totalPoints)}/><path className="automatic-line" d={path(reconciledPoints)}/>{totalPoints.map(([x,y],index)=><circle className="daily-point" key={daily[index].metric_date} cx={x} cy={y} r="3"/>)}{daily.map((item,index)=><text key={item.metric_date} x={daily.length===1?400:index*(800/(daily.length-1))} y="202" textAnchor={index===0?'start':index===daily.length-1?'end':'middle'}>{item.metric_date.slice(5)}</text>)}</svg><div className="history-legend"><span className="total">Total diário</span><span className="automatic">Reconciliados</span></div></section>}
    <section className="panel"><div className="panel-head"><div><h2>Importações V2</h2><p>Cada ficheiro só fica concluído após leitura, reconciliação e cálculo dos indicadores.</p></div></div><div className="table-wrap"><table><thead><tr><th>Período contabilístico</th><th>Ficheiro</th><th>Lidos</th><th>Inseridos</th><th>Duplicados</th><th>Rejeitados</th><th>Concluído em</th><th>Estado</th></tr></thead><tbody>{imports.map(item=><tr key={item.id}><td>{item.period_start??'—'} a {item.period_end??'—'}</td><td>{item.original_filename}</td><td>{item.source_rows.toLocaleString('pt-AO')}</td><td>{item.inserted_rows.toLocaleString('pt-AO')}</td><td>{item.duplicate_rows.toLocaleString('pt-AO')}</td><td>{item.rejected_rows.toLocaleString('pt-AO')}</td><td>{new Intl.DateTimeFormat('pt-AO',{dateStyle:'short',timeStyle:'short'}).format(new Date(item.completed_at??item.created_at))}</td><td><span className={`badge ${item.state==='completed'?'automatic':'unreconciled'}`}>{item.state==='completed'?'Concluída':item.stage}</span>{item.error_message&&<small className="import-failure">{item.error_message}</small>}</td></tr>)}</tbody></table></div></section>
  </div>;
}
