import {useCallback,useEffect,useRef,useState} from 'react';
import {AlertTriangle,CalendarDays,ChevronDown,ChevronUp,ChevronsDown,Clock3,Columns3,Database,FileSpreadsheet,FileText,LoaderCircle,Maximize2,Repeat2,Square,X} from 'lucide-react';
import {supabase} from '../lib/supabase';
import {logPlatformAction} from '../lib/database';
import {shiftOperationalDay} from '../lib/operationalDays';
import './v2-movements.css';

type StateFilter='open'|'reconciled'|'all';
type AgeFilter=null|0|1|2|3;
type SortKey='accounting_date'|'system_date'|'operation_number'|'raw_description'|'amount'|'balance'|'native_idtr'|'status'|'reconciliation_method';
type Movement={id:number;accounting_date:string;system_date:string|null;system_time:string|null;operation_number:string|null;raw_description:string|null;amount:number;balance:number|null;native_idtr:string|null;reference_26:string|null;status:string;reconciliation_method:string|null};
// As descrições são extensas; 250 linhas mantêm cada pedido abaixo do limite
// PostgREST mesmo com a base fria. As exportações percorrem o universo filtrado.
const PAGE=250;
const LOAD_ALL_PAGE=1000;
const errorMessage=(cause:unknown,fallback:string)=>cause instanceof Error?cause.message:typeof cause==='object'&&cause!==null&&'message' in cause?String((cause as {message:unknown}).message):fallback;
const EXPORT_COLUMNS=[
  {visible:'period',key:'accounting_date',header:'Período contabilístico',pdf:'Período',width:16},
  {visible:'system',key:'system_date',header:'Data sistema',pdf:'Sistema',width:14},
  {visible:'operation',key:'operation_number',header:'Operação',pdf:'Operação',width:20},
  {visible:'description',key:'raw_description',header:'Descrição original',pdf:'Descrição',width:48},
  {visible:'amount',key:'amount',header:'MRVLR',pdf:'MRVLR',width:18},
  {visible:'balance',key:'balance',header:'Saldo contabilístico',pdf:'Saldo',width:20},
  {visible:'idtr',key:'native_idtr',header:'IDTR nativo',pdf:'IDTR',width:28},
  {visible:'reference',key:'reference_26',header:'Referência /26',pdf:'/26',width:22},
  {visible:'status',key:'status',header:'Estado',pdf:'Estado',width:16},
  {visible:'method',key:'reconciliation_method',header:'Método',pdf:'Método',width:28},
] as const;
type ExportColumn=(typeof EXPORT_COLUMNS)[number];
const exportValue=(row:Movement,column:ExportColumn)=>column.visible==='system'?`${row.system_date??'—'} ${row.system_time??''}`:column.visible==='status'?(row.status==='reconciled'?'Reconciliado':'Pendente'):column.visible==='method'?(row.reconciliation_method==='idtr'?'IDTR':row.reconciliation_method==='operation_description'?'Operação + descrição + valor':row.reconciliation_method??'—'):column.visible==='amount'?Number(row.amount).toFixed(2):column.visible==='balance'?(row.balance===null?'—':Number(row.balance).toFixed(2)):String(row[column.key]??'—');
const localDate=(date:string|null,time='00:00:00')=>{if(!date)return null;const [year,month,day]=date.split('-').map(Number),[hour,minute,second]=time.split(':').map(Number);return new Date(year,month-1,day,hour||0,minute||0,second||0)};
const excelValue=(row:Movement,column:ExportColumn)=>column.visible==='period'?localDate(row.accounting_date):column.visible==='system'?localDate(row.system_date,row.system_time??'00:00:00'):column.visible==='amount'?Number(row.amount):column.visible==='balance'?(row.balance===null?null:Number(row.balance)):exportValue(row,column);
export default function V2Movements({revision=0}:{revision?:number}){
  const [seriesId,setSeriesId]=useState<string|null>(null),[filter,setFilter]=useState<StateFilter>('open'),[rows,setRows]=useState<Movement[]>([]),[total,setTotal]=useState(0),[counts,setCounts]=useState({all:0,open:0,reconciled:0}),[loading,setLoading]=useState(true),[loadingMore,setLoadingMore]=useState(false),[loadingAll,setLoadingAll]=useState<null|{processed:number}>(null),[error,setError]=useState('');
  const [sortKey,setSortKey]=useState<SortKey>('accounting_date'),[sortAsc,setSortAsc]=useState(false),[dateFrom,setDateFrom]=useState(''),[dateTo,setDateTo]=useState('');
  const [ageFilter,setAgeFilter]=useState<AgeFilter>(null),[ageCounts,setAgeCounts]=useState({latestDate:'',sameDay:0,atLeast1:0,atLeast2:0,atLeast3:0});
  const [exporting,setExporting]=useState<null|{kind:'excel'|'pdf';processed:number}>(null);
  const [columnMenu,setColumnMenu]=useState(false),[visible,setVisible]=useState<Record<string,boolean>>({period:true,system:true,operation:true,description:true,amount:true,balance:true,idtr:true,reference:true,status:true,method:true});
  const [fitScreen,setFitScreen]=useState(false);
  const columnMenuRef=useRef<HTMLDivElement>(null);
  const cancelLoadAllRef=useRef(false);
  useEffect(()=>{if(exporting||loadingAll)document.body.dataset.appBusy='true';return()=>{if(exporting||loadingAll)document.body.dataset.appBusy='false'}},[exporting,loadingAll]);
  useEffect(()=>{const close=(event:MouseEvent)=>{if(columnMenuRef.current&&!columnMenuRef.current.contains(event.target as Node))setColumnMenu(false)};document.addEventListener('mousedown',close);return()=>document.removeEventListener('mousedown',close)},[]);
  useEffect(()=>{let active=true;void supabase.from('rt_v2_series').select('id').order('created_at',{ascending:true}).limit(1).maybeSingle().then(({data,error})=>{if(!active)return;if(error)setError(error.message);else setSeriesId(data?.id??null);});return()=>{active=false};},[]);
  const load=useCallback(async(reset:boolean)=>{if(!seriesId)return;reset?setLoading(true):setLoadingMore(true);setError('');try{
    let query=supabase.from('rt_v2_movements').select('id,accounting_date,system_date,system_time,operation_number,raw_description,amount,balance,native_idtr,reference_26,status,reconciliation_method').eq('series_id',seriesId);
    if(filter!=='all')query=query.eq('status',filter);if(dateFrom)query=query.gte('accounting_date',dateFrom);if(dateTo)query=query.lte('accounting_date',dateTo);if(ageFilter!==null&&ageCounts.latestDate){const date=shiftOperationalDay(ageCounts.latestDate,-ageFilter);query=ageFilter===0?query.eq('accounting_date',date):query.lte('accounting_date',date);}query=query.order(sortKey,{ascending:sortAsc}).order('id',{ascending:sortAsc});const from=reset?0:rows.length,response=await query.range(from,from+PAGE-1);if(response.error)throw response.error;setRows(previous=>reset?(response.data as Movement[]):[...previous,...(response.data as Movement[])]);
  }catch(cause){setError(errorMessage(cause,'Não foi possível carregar os movimentos.'));}finally{setLoading(false);setLoadingMore(false);}},[seriesId,filter,rows.length,dateFrom,dateTo,sortKey,sortAsc,ageFilter,ageCounts.latestDate]);
  useEffect(()=>{if(!seriesId)return;void supabase.rpc('rt_v2_movement_metrics',{p_series_id:seriesId}).then(({data,error})=>{if(error){setError(error.message);return;}const totals=((data as Record<string,unknown>|null)?.totals??{}) as Record<string,unknown>;setCounts({all:Number(totals.movements??0),open:Number(totals.open??0),reconciled:Number(totals.reconciled??0)});});},[seriesId,revision]);
  useEffect(()=>{if(!seriesId)return;void supabase.rpc('rt_v2_open_age_metrics',{p_series_id:seriesId}).then(({data,error})=>{if(error)return;const value=(data??{}) as Record<string,unknown>;setAgeCounts({latestDate:String(value.latest_date??''),sameDay:Number(value.same_day??0),atLeast1:Number(value.at_least_1??0),atLeast2:Number(value.at_least_2??0),atLeast3:Number(value.at_least_3??0)});});},[seriesId,counts.open,revision]);
  useEffect(()=>{if(ageFilter!==null&&!dateFrom&&!dateTo){setTotal(ageFilter===0?ageCounts.sameDay:ageFilter===1?ageCounts.atLeast1:ageFilter===2?ageCounts.atLeast2:ageCounts.atLeast3);return}if(!dateFrom&&!dateTo){setTotal(filter==='all'?counts.all:filter==='open'?counts.open:counts.reconciled);return}if(!seriesId)return;let query=supabase.from('rt_v2_movements').select('id',{count:'exact',head:true}).eq('series_id',seriesId);if(filter!=='all')query=query.eq('status',filter);if(dateFrom)query=query.gte('accounting_date',dateFrom);if(dateTo)query=query.lte('accounting_date',dateTo);void query.then(({count,error})=>error?setError(error.message):setTotal(count??0));},[counts,filter,seriesId,dateFrom,dateTo,ageFilter,ageCounts]);
  useEffect(()=>{if(seriesId)void load(true);},[seriesId,filter,dateFrom,dateTo,sortKey,sortAsc,ageFilter,ageCounts.latestDate,revision]);
  const choose=(value:StateFilter)=>{cancelLoadAllRef.current=true;setRows([]);setAgeFilter(null);setFilter(value)};
  const chooseAge=(value:AgeFilter)=>{cancelLoadAllRef.current=true;setRows([]);setDateFrom('');setDateTo('');setFilter('open');setAgeFilter(value)};
  const sort=(key:SortKey)=>{cancelLoadAllRef.current=true;setRows([]);if(sortKey===key)setSortAsc(value=>!value);else{setSortKey(key);setSortAsc(true)}};
  const heading=(label:string,key:SortKey)=><button type="button" onClick={()=>sort(key)}>{label}{sortKey===key?(sortAsc?<ChevronUp/>:<ChevronDown/>):null}</button>;
  const collectFiltered=async(limit=Number.POSITIVE_INFINITY)=>{if(!seriesId)return[];const collected:Movement[]=[];for(let from=0;from<Math.min(total,limit);from+=PAGE){let query=supabase.from('rt_v2_movements').select('id,accounting_date,system_date,system_time,operation_number,raw_description,amount,balance,native_idtr,reference_26,status,reconciliation_method').eq('series_id',seriesId);if(filter!=='all')query=query.eq('status',filter);if(dateFrom)query=query.gte('accounting_date',dateFrom);if(dateTo)query=query.lte('accounting_date',dateTo);if(ageFilter!==null&&ageCounts.latestDate){const date=shiftOperationalDay(ageCounts.latestDate,-ageFilter);query=ageFilter===0?query.eq('accounting_date',date):query.lte('accounting_date',date);}const response=await query.order(sortKey,{ascending:sortAsc}).order('id',{ascending:sortAsc}).range(from,Math.min(from+PAGE-1,limit-1));if(response.error)throw response.error;const page=response.data as Movement[];collected.push(...page);setExporting(value=>value?{...value,processed:collected.length}:value);if(page.length<PAGE)break;}return collected};
  const loadAll=async()=>{if(!seriesId||rows.length>=total)return;cancelLoadAllRef.current=false;setError('');setLoadingAll({processed:rows.length});try{const collected:Movement[]=[];for(let from=0;from<total;from+=LOAD_ALL_PAGE){if(cancelLoadAllRef.current)return;let query=supabase.from('rt_v2_movements').select('id,accounting_date,system_date,system_time,operation_number,raw_description,amount,balance,native_idtr,reference_26,status,reconciliation_method').eq('series_id',seriesId);if(filter!=='all')query=query.eq('status',filter);if(dateFrom)query=query.gte('accounting_date',dateFrom);if(dateTo)query=query.lte('accounting_date',dateTo);if(ageFilter!==null&&ageCounts.latestDate){const date=shiftOperationalDay(ageCounts.latestDate,-ageFilter);query=ageFilter===0?query.eq('accounting_date',date):query.lte('accounting_date',date);}const response=await query.order(sortKey,{ascending:sortAsc}).order('id',{ascending:sortAsc}).range(from,Math.min(from+LOAD_ALL_PAGE-1,total-1));if(response.error)throw response.error;const page=response.data as Movement[];collected.push(...page);setLoadingAll({processed:collected.length});if(page.length<LOAD_ALL_PAGE)break;}if(!cancelLoadAllRef.current)setRows(collected);}catch(cause){setError(errorMessage(cause,'Não foi possível carregar todos os movimentos.'));}finally{setLoadingAll(null);cancelLoadAllRef.current=false;}};
  const save=(blob:Blob,name:string)=>{const url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download=name;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
  const exportExcel=async()=>{setError('');setExporting({kind:'excel',processed:0});try{
    const data=await collectFiltered(),columns=EXPORT_COLUMNS.filter(column=>visible[column.visible]);if(!columns.length)throw new Error('Selecione pelo menos uma coluna antes de exportar.');const ExcelJS=await import('exceljs'),workbook=new ExcelJS.Workbook(),sheet=workbook.addWorksheet('Movimentos');
    sheet.views=[{state:'frozen',ySplit:1}];sheet.columns=columns.map(column=>({header:column.header,key:column.visible,width:column.width,style:column.visible==='period'?{numFmt:'dd/mm/yyyy'}:column.visible==='system'?{numFmt:'dd/mm/yyyy hh:mm:ss'}:column.visible==='amount'||column.visible==='balance'?{numFmt:'#,##0.00;[Red]-#,##0.00'}:undefined}));for(const row of data)sheet.addRow(Object.fromEntries(columns.map(column=>[column.visible,excelValue(row,column)])));
    sheet.getRow(1).font={bold:true,color:{argb:'FFFFFFFF'}};sheet.getRow(1).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF087554'}};if(columns.length)sheet.autoFilter={from:'A1',to:`${sheet.getColumn(columns.length).letter}1`};
    const buffer=await workbook.xlsx.writeBuffer();save(new Blob([buffer],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),`movimentos-${filter}-${new Date().toISOString().slice(0,10)}.xlsx`);await logPlatformAction('v2_export_excel','movement_export',{rows:data.length,filter,dateFrom,dateTo,ageFilter,sortKey,sortAsc,columns:columns.map(column=>column.visible)});
  }catch(cause){setError(errorMessage(cause,'Não foi possível exportar para Excel.'));}finally{setExporting(null)}};
  const exportPdf=async()=>{if(total>20000){setError(`O filtro contém ${total.toLocaleString('pt-AO')} movimentos. Para garantir um PDF legível e estável, reduza o período para 20.000 movimentos ou menos.`);return}setError('');setExporting({kind:'pdf',processed:0});try{
    const data=await collectFiltered(20000),columns=EXPORT_COLUMNS.filter(column=>visible[column.visible]);if(!columns.length)throw new Error('Selecione pelo menos uma coluna antes de exportar.');const [{jsPDF},{default:autoTable}]=await Promise.all([import('jspdf'),import('jspdf-autotable')]),doc=new jsPDF({orientation:'landscape',unit:'mm',format:'a4'});doc.setFontSize(10);doc.text(`Movimentos · ${filter} · ${data.length.toLocaleString('pt-AO')} linhas`,8,8);
    autoTable(doc,{startY:12,margin:{left:5,right:5},styles:{fontSize:5,cellPadding:1,overflow:'linebreak'},head:[columns.map(column=>column.pdf)],body:data.map(row=>columns.map(column=>exportValue(row,column))),tableWidth:'auto',horizontalPageBreak:false});doc.save(`movimentos-${filter}-${new Date().toISOString().slice(0,10)}.pdf`);await logPlatformAction('v2_export_pdf','movement_export',{rows:data.length,filter,dateFrom,dateTo,ageFilter,sortKey,sortAsc,columns:columns.map(column=>column.visible)});
  }catch(cause){setError(errorMessage(cause,'Não foi possível exportar para PDF.'));}finally{setExporting(null)}};
  return <section className={`panel v2-movements ${fitScreen?'fit-screen':''}`}>
    <div className="v2-movement-summary"><button className={filter==='open'?'active warn':''} onClick={()=>choose('open')}><Clock3/><span>Pendentes</span><strong>{counts.open.toLocaleString('pt-AO')}</strong></button><button className={filter==='reconciled'?'active good':''} onClick={()=>choose('reconciled')}><Repeat2/><span>Reconciliados</span><strong>{counts.reconciled.toLocaleString('pt-AO')}</strong></button><button className={filter==='all'?'active total':''} onClick={()=>choose('all')}><Database/><span>Todos</span><strong>{counts.all.toLocaleString('pt-AO')}</strong></button></div>
    <div className="v2-age-filters" aria-label="Antiguidade dos movimentos pendentes"><span>Pendentes por antiguidade</span><button className={ageFilter===0?'active d0':'d0'} onClick={()=>chooseAge(0)}>Próprio dia <strong>{ageCounts.sameDay.toLocaleString('pt-AO')}</strong></button><button className={ageFilter===1?'active d1':'d1'} onClick={()=>chooseAge(1)}>Há pelo menos 1 dia <strong>{ageCounts.atLeast1.toLocaleString('pt-AO')}</strong></button><button className={ageFilter===2?'active d2':'d2'} onClick={()=>chooseAge(2)}>Há pelo menos 2 dias <strong>{ageCounts.atLeast2.toLocaleString('pt-AO')}</strong></button><button className={ageFilter===3?'active d3':'d3'} onClick={()=>chooseAge(3)}>Há pelo menos 3 dias <strong>{ageCounts.atLeast3.toLocaleString('pt-AO')}</strong></button><button className={ageFilter===null&&filter==='open'?'active all':'all'} onClick={()=>chooseAge(null)}>Todos os pendentes <strong>{counts.open.toLocaleString('pt-AO')}</strong></button></div>
    <div className="panel-head"><div><h2>Movimentos</h2><p>O filtro corresponde a <strong>{total.toLocaleString('pt-AO')}</strong> movimentos; estão visíveis {rows.length.toLocaleString('pt-AO')}.</p></div>{loading&&<LoaderCircle className="spinning"/>}</div>
    {(loading||loadingMore||loadingAll||exporting)&&<div className="v2-table-progress" role="status"><LoaderCircle className="spinning"/><div><strong>{exporting?`A preparar ${exporting.kind==='excel'?'Excel':'PDF'}`:loadingAll?'A carregar todos os movimentos':loadingMore?'A carregar mais movimentos':'A consultar a base de dados'}</strong><span>{exporting?`${exporting.processed.toLocaleString('pt-AO')} de ${total.toLocaleString('pt-AO')} movimentos`:loadingAll?`${loadingAll.processed.toLocaleString('pt-AO')} de ${total.toLocaleString('pt-AO')} movimentos carregados`:loadingMore?`${rows.length.toLocaleString('pt-AO')} de ${total.toLocaleString('pt-AO')} movimentos visíveis`:'A aplicar filtros e ordenação…'}</span><i><b style={{width:`${exporting?Math.min(100,(exporting.processed/Math.max(1,total))*100):loadingAll?Math.min(100,(loadingAll.processed/Math.max(1,total))*100):loadingMore?Math.min(100,(rows.length/Math.max(1,total))*100):18}%`}}/></i></div><em>{exporting||loadingAll||loadingMore?`${Math.round((exporting?exporting.processed:loadingAll?loadingAll.processed:rows.length)/Math.max(1,total)*100)}%`:'…'}</em>{loadingAll&&<button type="button" className="secondary-button" onClick={()=>{cancelLoadAllRef.current=true}}><Square/>Cancelar</button>}</div>}
    <div className="v2-date-filters"><label><CalendarDays/>De <input type="date" value={dateFrom} max={dateTo||undefined} onChange={event=>{setAgeFilter(null);setDateFrom(event.target.value)}}/></label><label>Até <input type="date" value={dateTo} min={dateFrom||undefined} onChange={event=>{setAgeFilter(null);setDateTo(event.target.value)}}/></label>{(dateFrom||dateTo)&&<button type="button" onClick={()=>{setDateFrom('');setDateTo('')}}><X/>Limpar datas</button>}<span className="v2-export-spacer"/><button type="button" className={fitScreen?'active':''} onClick={()=>setFitScreen(value=>!value)} title="Ajustar colunas à largura do ecrã"><Maximize2/>Ajustar ao ecrã</button><div className="v2-column-picker" ref={columnMenuRef}><button type="button" onClick={()=>setColumnMenu(value=>!value)}><Columns3/>Colunas</button>{columnMenu&&<div><header><strong>Colunas visíveis</strong><button type="button" onClick={()=>setVisible(Object.fromEntries(Object.keys(visible).map(key=>[key,true])))}>Todas</button><button type="button" onClick={()=>setVisible(Object.fromEntries(Object.keys(visible).map(key=>[key,false])))}>Limpar</button></header>{[['period','Período contabilístico'],['system','Data/hora sistema'],['operation','Operação'],['description','Descrição original'],['amount','MRVLR'],['balance','Saldo contabilístico'],['idtr','IDTR nativo'],['reference','Referência /26'],['status','Estado'],['method','Método']].map(([key,label])=><label key={key}><input type="checkbox" checked={visible[key]} onChange={()=>setVisible(value=>({...value,[key]:!value[key]}))}/>{label}</label>)}</div>}</div><button type="button" disabled={!total||!!exporting} onClick={()=>void exportExcel()}><FileSpreadsheet/>{exporting?.kind==='excel'?`Excel ${exporting.processed.toLocaleString('pt-AO')} / ${total.toLocaleString('pt-AO')}`:'Excel'}</button><button type="button" disabled={!total||!!exporting} onClick={()=>void exportPdf()}><FileText/>{exporting?.kind==='pdf'?`PDF ${exporting.processed.toLocaleString('pt-AO')} / ${total.toLocaleString('pt-AO')}`:'PDF'}</button></div>
    {error&&<div className="error"><AlertTriangle size={18}/>{error}</div>}
    <div className="table-wrap"><table><thead><tr>{visible.period&&<th>{heading('Período contabilístico','accounting_date')}</th>}{visible.system&&<th>{heading('Data/hora sistema','system_date')}</th>}{visible.operation&&<th>{heading('Operação','operation_number')}</th>}{visible.description&&<th>{heading('Descrição original','raw_description')}</th>}{visible.amount&&<th>{heading('MRVLR','amount')}</th>}{visible.balance&&<th>{heading('Saldo contabilístico','balance')}</th>}{visible.idtr&&<th>{heading('IDTR nativo','native_idtr')}</th>}{visible.reference&&<th>Referência /26</th>}{visible.status&&<th>{heading('Estado','status')}</th>}{visible.method&&<th>{heading('Método','reconciliation_method')}</th>}</tr></thead><tbody>{rows.map(row=><tr key={row.id}>{visible.period&&<td>{row.accounting_date}</td>}{visible.system&&<td>{row.system_date??'—'} {row.system_time??''}</td>}{visible.operation&&<td className="mono">{row.operation_number??'—'}</td>}{visible.description&&<td>{row.raw_description??'—'}</td>}{visible.amount&&<td className="amount">{Number(row.amount).toLocaleString('pt-AO',{minimumFractionDigits:2,maximumFractionDigits:2})}</td>}{visible.balance&&<td className="amount">{row.balance===null?'—':Number(row.balance).toLocaleString('pt-AO',{minimumFractionDigits:2,maximumFractionDigits:2})}</td>}{visible.idtr&&<td className="mono">{row.native_idtr??'—'}</td>}{visible.reference&&<td className="mono">{row.reference_26??'—'}</td>}{visible.status&&<td><span className={`badge ${row.status==='reconciled'?'automatic':'unreconciled'}`}>{row.status==='reconciled'?'Reconciliado':'Pendente'}</span></td>}{visible.method&&<td>{row.reconciliation_method==='idtr'?'IDTR':row.reconciliation_method==='operation_description'?'Operação + descrição + valor':row.reconciliation_method??'—'}</td>}</tr>)}</tbody></table></div>
    {rows.length<total&&<footer><button className="primary-button" disabled={loadingMore||!!loadingAll} onClick={()=>void load(false)}>{loadingMore?<><LoaderCircle className="spinning"/> A carregar…</>:`Carregar mais ${Math.min(PAGE,total-rows.length).toLocaleString('pt-AO')} linhas`}</button><button className="secondary-button load-all" disabled={loadingMore||!!loadingAll} onClick={()=>void loadAll()}><ChevronsDown/>Carregar todas as {total.toLocaleString('pt-AO')} linhas</button><span>{rows.length.toLocaleString('pt-AO')} / {total.toLocaleString('pt-AO')}</span></footer>}
  </section>;
}
