import {useEffect,useState} from 'react';
import {AlertTriangle,Clock3,Layers3,Repeat2,X} from 'lucide-react';
import {loadV2BalanceAnomalies,loadV2MissingBusinessDays,type V2BalanceAnomaly,type V2Dashboard} from './database';
import './v2-results.css';

const number=(value:unknown)=>Number(value??0);
export default function V2Results({dashboard}:{dashboard:V2Dashboard}){
  const [excludeOpening,setExcludeOpening]=useState(true),[anomalies,setAnomalies]=useState<V2BalanceAnomaly[]|null>(null),[anomalyError,setAnomalyError]=useState(''),[loadingAnomalies,setLoadingAnomalies]=useState(false),[missingDays,setMissingDays]=useState<string[]>([]),[showMissing,setShowMissing]=useState(false);
  useEffect(()=>{let active=true;void loadV2MissingBusinessDays().then(days=>{if(active)setMissingDays(days)}).catch(()=>undefined);return()=>{active=false}},[dashboard.calculatedAt]);
  const result=dashboard.result??{},totals=(result.totals??{}) as Record<string,unknown>,ages=(result.openByAge??{}) as Record<string,unknown>,delays=(result.reconciledByDelay??{}) as Record<string,unknown>,reconciliations=(result.reconciliationsByDelay??{}) as Record<string,unknown>,balance=(result.balanceSummary??{}) as Record<string,unknown>;
  const cards=[['Total',number(totals.movements),Layers3,'total'],['Reconciliados',number(totals.reconciled),Repeat2,'good'],['Em aberto',number(totals.open),Clock3,'warn'],['Com anomalias no saldo',number(totals.balance_anomalies),AlertTriangle,'bad']] as const;
  const ageKeys=['D+0','D+1','D+2','D+3','D+4–7','D+8+'],delayKeys=['D+0','D+1','D+2','D+3','D+4+'];
  const openTotal=ageKeys.reduce((sum,key)=>sum+number(ages[key]),0);
  const reconciledMovementTotal=delayKeys.reduce((sum,key)=>sum+number(delays[key]),0);
  const grossBalance=number(balance.grossOpenBalance),openingBalance=number(balance.openingBoundaryBalance),displayBalance=excludeOpening?number(balance.adjustedOpenBalance):grossBalance;
  const maxBalance=Math.max(1,Math.abs(grossBalance),Math.abs(openingBalance),Math.abs(displayBalance)),barWidth=Math.min(50,Math.abs(displayBalance)/maxBalance*50);
  const showAnomalies=async()=>{setAnomalyError('');setLoadingAnomalies(true);try{setAnomalies(await loadV2BalanceAnomalies());}catch(cause){setAnomalyError(cause instanceof Error?cause.message:'Não foi possível carregar as anomalias.');setAnomalies([]);}finally{setLoadingAnomalies(false);}};
  return <div className="results-shell v2-results">
    {missingDays.length>0&&<button type="button" className={`v2-coverage-alert ${showMissing?'expanded':''}`} onClick={()=>setShowMissing(value=>!value)}><AlertTriangle/><span><strong>ATENÇÃO — EXISTEM DIAS ÚTEIS SEM MOVIMENTOS NA SÉRIE</strong><small>{missingDays.length.toLocaleString('pt-AO')} {missingDays.length===1?'dia por confirmar':'dias por confirmar'} · clique para {showMissing?'ocultar':'ver as datas'}</small>{showMissing&&<em>{missingDays.map(date=>new Intl.DateTimeFormat('pt-PT').format(new Date(`${date}T00:00:00Z`))).join(' · ')}</em>}</span></button>}
    <section className="v2-result-head"><div><h2>Análise</h2></div><p>Atualizada em {dashboard.calculatedAt?new Date(dashboard.calculatedAt).toLocaleString('pt-PT'):'—'}.</p></section>
    <p className="eyebrow v2-metrics-label">MOVIMENTOS</p>
    <section className="v2-main-metrics">{cards.map(([label,value,Icon,tone])=>{const interactive=tone==='bad'&&value>0;return <article className={`v2-kpi ${tone}${interactive?' interactive':''}`} key={label} role={interactive?'button':undefined} tabIndex={interactive?0:undefined} title={interactive?'Abrir o detalhe das anomalias':undefined} onClick={interactive?()=>void showAnomalies():undefined} onKeyDown={interactive?event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();void showAnomalies()}}:undefined}><span className="v2-kpi-icon"><Icon size={19}/></span><div><small>{label}</small><strong>{value.toLocaleString('pt-AO')}</strong>{label==='Total'&&<span className="v2-kpi-detail">{number(totals.with_idtr).toLocaleString('pt-AO')} com IDTR · {number(totals.without_idtr).toLocaleString('pt-AO')} sem IDTR ( /26)</span>}{label==='Reconciliados'&&<span className="v2-kpi-detail">{number(totals.reconciled_idtr).toLocaleString('pt-AO')} por IDTR · {number(totals.reconciled_without_idtr).toLocaleString('pt-AO')} sem IDTR</span>}</div></article>})}</section>
    <section className="v2-balance-summary">
      <div><p className="eyebrow">SALDO DOS MOVIMENTOS EM ABERTO</p><strong>{displayBalance.toLocaleString('pt-AO',{minimumFractionDigits:2,maximumFractionDigits:2})}</strong><small>{excludeOpening?'Sem a fronteira inicial':'Com a fronteira inicial'} · valor original MRVLR</small></div>
      <div className="v2-diverging" aria-label={`Saldo líquido ${displayBalance.toFixed(2)}`}><i className="negative" style={{width:displayBalance<0?`${barWidth}%`:'0'}}/><b/><i className="positive" style={{width:displayBalance>0?`${barWidth}%`:'0'}}/></div>
      <dl><div><dt>Saldo bruto</dt><dd>{grossBalance.toLocaleString('pt-AO',{minimumFractionDigits:2})}</dd></div><div><dt>Impacto da fronteira inicial</dt><dd>{openingBalance.toLocaleString('pt-AO',{minimumFractionDigits:2})}</dd></div></dl>
      <button type="button" className={`boundary-toggle ${excludeOpening?'active':''}`} onClick={()=>setExcludeOpening(value=>!value)}><i/><span>{excludeOpening?'Fronteira inicial excluída':'Fronteira inicial incluída'}</span></button>
    </section>
    <button type="button" className="v2-anomaly-link" disabled={!number(totals.balance_anomalies)||loadingAnomalies} onClick={()=>void showAnomalies()}><AlertTriangle size={17}/>{loadingAnomalies?'A carregar detalhe…':`Ver detalhe das ${number(totals.balance_anomalies).toLocaleString('pt-AO')} anomalias de saldo`}</button>
    <div className="v2-compact-panels">
      <section className="v2-compact-panel"><header><div><p className="eyebrow">MOVIMENTOS</p><h3>Abertos por antiguidade</h3></div><Clock3 size={20}/></header><div className="v2-bucket-grid">{ageKeys.map((key,index)=>{const value=number(ages[key]),rate=openTotal?value/openTotal*100:0;return <article className={`traffic-${Math.min(index,3)}`} key={key}><span>{key}</span><strong>{value.toLocaleString('pt-AO')}</strong><small>{rate.toFixed(1)}% dos movimentos abertos</small><div className="v2-percent-track"><i style={{width:`${rate}%`}}/></div></article>})}</div></section>
      <section className="v2-compact-panel"><header><div><p className="eyebrow">RECONCILIAÇÃO</p><h3>Movimentos fechados por prazo</h3></div><div className="v2-average-delay"><Repeat2 size={20}/><span>Média</span><strong>{number(result.averageReconciliationDays).toLocaleString('pt-AO',{maximumFractionDigits:2})} dias</strong></div></header><div className="v2-bucket-grid five">{delayKeys.map((key,index)=>{const movements=number(delays[key]),closed=number(reconciliations[key]),rate=reconciledMovementTotal?movements/reconciledMovementTotal*100:0;return <article className={`closed-${Math.min(index,3)}`} key={key}><span>{key}</span><strong>{rate.toFixed(1)}%</strong><small>{closed.toLocaleString('pt-AO')} reconciliações <em>({movements.toLocaleString('pt-AO')} movimentos)</em></small><div className="v2-percent-track"><i style={{width:`${rate}%`}}/></div></article>})}</div></section>
    </div>
    {anomalies!==null&&<div className="v2-modal-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)setAnomalies(null)}}><section className="v2-anomaly-modal" role="dialog" aria-modal="true" aria-label="Anomalias de sequência de saldo"><header><div><p className="eyebrow">AUDITORIA CONTABILÍSTICA</p><h3>Anomalias na evolução do saldo</h3></div><button type="button" onClick={()=>setAnomalies(null)} aria-label="Fechar"><X size={20}/></button></header><p>Linhas em que o saldo recebido não corresponde ao saldo anterior mais o valor original MRVLR.</p>{anomalyError?<div className="error">{anomalyError}</div>:<div className="table-wrap"><table><thead><tr><th>Data</th><th>Operação</th><th>Descrição</th><th>MRVLR</th><th>Saldo recebido</th><th>Saldo esperado</th></tr></thead><tbody>{anomalies.map(row=><tr key={row.id}><td>{row.accounting_date}</td><td className="mono">{row.operation_number??'—'}</td><td>{row.raw_description??'—'}</td><td className="amount">{number(row.amount).toLocaleString('pt-AO',{minimumFractionDigits:2})}</td><td className="amount">{row.balance===null?'—':number(row.balance).toLocaleString('pt-AO',{minimumFractionDigits:2})}</td><td className="amount">{row.expected_balance===null?'—':number(row.expected_balance).toLocaleString('pt-AO',{minimumFractionDigits:2})}</td></tr>)}</tbody></table></div>}</section></div>}
  </div>;
}
