import {useEffect,useMemo,useState} from 'react';
import {Check,ChevronDown,ChevronRight,RefreshCw,X} from 'lucide-react';
import {supabase} from '../lib/supabase';
import './confirmation-overrides.css';

type Status='pending'|'approved'|'rejected'|'superseded';
type Proposal={id:string;method:'operation'|'operation_description';reconciliation_key:string;movement_count:number;balance:number;first_accounting_date:string;last_accounting_date:string;operational_delay:number;status:Status;reviewed_at:string|null;review_note:string|null;created_at:string};
type Movement={id:number;accounting_date:string;system_date:string|null;operation_number:string|null;raw_description:string|null;amount:number;native_idtr:string|null;status:string};

const money=(value:number)=>Number(value).toLocaleString('pt-AO',{style:'currency',currency:'AOA'});
const methodLabel=(method:Proposal['method'])=>method==='operation'?'Mesmo número de operação · soma zero':'Operação + descrição comparável · soma zero';
const isAutomaticIdtr=(proposal:Proposal)=>proposal.status==='approved'&&proposal.review_note?.startsWith('Confirmação automática: todas as linhas têm o mesmo IDTR')===true;

export default function V2ReconciliationReview({canReview=true}:{canReview?:boolean}){
  const [seriesId,setSeriesId]=useState('');const [rows,setRows]=useState<Proposal[]>([]);const [status,setStatus]=useState<Status>('pending');
  const [method,setMethod]=useState<'all'|Proposal['method']>('all');const [age,setAge]=useState<'all'|'0-1'|'2-7'|'8+'>('all');
  const [totalAvailable,setTotalAvailable]=useState(0);const [totalMovementCount,setTotalMovementCount]=useState(0);
  const [selected,setSelected]=useState<Set<string>>(new Set());const [expanded,setExpanded]=useState<Set<string>>(new Set());const [details,setDetails]=useState<Record<string,Movement[]>>({});
  const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState('');
  const load=async()=>{setLoading(true);setError('');try{let id=seriesId;if(!id){const series=await supabase.from('rt_v2_series').select('id').order('created_at',{ascending:true}).limit(1).maybeSingle();if(series.error)throw series.error;id=series.data?.id??'';setSeriesId(id);}if(!id){setRows([]);return;}let query=supabase.from('rt_v2_reconciliation_proposals').select('id,method,reconciliation_key,movement_count,balance,first_accounting_date,last_accounting_date,operational_delay,status,reviewed_at,review_note,created_at').eq('series_id',id).eq('status',status);let summary=supabase.from('rt_v2_reconciliation_proposal_summary').select('proposals,movements').eq('series_id',id).eq('status',status);if(method!=='all'){query=query.eq('method',method);summary=summary.eq('method',method)}if(age==='0-1'){query=query.lte('operational_delay',1);summary=summary.lte('operational_delay',1)}if(age==='2-7'){query=query.gte('operational_delay',2).lte('operational_delay',7);summary=summary.gte('operational_delay',2).lte('operational_delay',7)}if(age==='8+'){query=query.gte('operational_delay',8);summary=summary.gte('operational_delay',8)}const [response,summaryResponse]=await Promise.all([query.order('operational_delay',{ascending:false}).order('created_at',{ascending:true}).limit(500),summary]);if(response.error)throw response.error;if(summaryResponse.error)throw summaryResponse.error;const proposals=(response.data??[]) as Proposal[];setRows(proposals);setExpanded(new Set(proposals.map(proposal=>proposal.id)));void loadDetails(proposals);setTotalAvailable((summaryResponse.data??[]).reduce((sum,row)=>sum+Number(row.proposals),0));setTotalMovementCount((summaryResponse.data??[]).reduce((sum,row)=>sum+Number(row.movements),0));setSelected(new Set());}catch(cause){setError(cause instanceof Error?cause.message:'Não foi possível carregar as confirmações.');}finally{setLoading(false)}};
  useEffect(()=>{void load()},[status,method,age]);
  const totalMovements=useMemo(()=>rows.reduce((sum,row)=>sum+row.movement_count,0),[rows]);
  const loadDetails=async(proposals:Proposal[])=>{const missing=proposals.filter(proposal=>!details[proposal.id]);if(!missing.length)return;try{const links:Array<{proposal_id:string;movement_id:number}>=[];for(let from=0;from<missing.length;from+=50){const response=await supabase.from('rt_v2_proposal_movements').select('proposal_id,movement_id').in('proposal_id',missing.slice(from,from+50).map(proposal=>proposal.id));if(response.error)throw response.error;links.push(...(response.data??[]) as typeof links)}const ids=[...new Set(links.map(link=>link.movement_id))];const movements:Movement[]=[];for(let from=0;from<ids.length;from+=500){const response=await supabase.from('rt_v2_movements').select('id,accounting_date,system_date,operation_number,raw_description,amount,native_idtr,status').in('id',ids.slice(from,from+500)).order('accounting_date',{ascending:true}).order('id',{ascending:true});if(response.error)throw response.error;movements.push(...(response.data??[]) as Movement[])}const byId=new Map(movements.map(movement=>[movement.id,movement]));const next:Record<string,Movement[]>={};for(const proposal of missing)next[proposal.id]=links.filter(link=>link.proposal_id===proposal.id).map(link=>byId.get(link.movement_id)).filter((movement):movement is Movement=>Boolean(movement));setDetails(value=>({...value,...next}));}catch(cause){setError(cause instanceof Error?cause.message:'Não foi possível carregar os movimentos associados.')}};
  const toggleDetails=(proposal:Proposal)=>{setExpanded(current=>{const next=new Set(current);next.has(proposal.id)?next.delete(proposal.id):next.add(proposal.id);return next});if(!details[proposal.id])void loadDetails([proposal])};
  const decide=async(ids:string[],decision:'approve'|'reject')=>{if(!ids.length||saving)return;setSaving(true);setError('');try{const response=await supabase.rpc('review_rt_v2_reconciliation_proposals',{p_proposal_ids:ids,p_decision:decision,p_note:null});if(response.error)throw response.error;await load();}catch(cause){setError(cause instanceof Error?cause.message:'Não foi possível guardar a decisão.');}finally{setSaving(false)}};
  const selectAll=()=>setSelected(selected.size===rows.length?new Set():new Set(rows.map(row=>row.id)));
  return <section className="confirmation-page">
    <div className="confirmation-summary"><article><span>Propostas no filtro</span><strong>{totalAvailable.toLocaleString('pt-AO')}</strong><small>{rows.length.toLocaleString('pt-AO')} visíveis nesta página</small></article><article><span>Movimentos no filtro</span><strong>{totalMovementCount.toLocaleString('pt-AO')}</strong><small>{totalMovements.toLocaleString('pt-AO')} visíveis nesta página</small></article><article><span>Regra de segurança</span><strong>Saldo 0,00</strong></article></div>
    <div className="confirmation-toolbar"><select value={status} onChange={event=>setStatus(event.target.value as Status)}><option value="pending">Pendentes de confirmação</option><option value="approved">Reconciliações concluídas</option><option value="rejected">Rejeitadas</option></select><select value={method} onChange={event=>setMethod(event.target.value as typeof method)}><option value="all">Todos os critérios</option><option value="operation">Número de operação</option><option value="operation_description">Operação + descrição</option></select><select value={age} onChange={event=>setAge(event.target.value as typeof age)}><option value="all">Todas as idades</option><option value="0-1">D+0 a D+1</option><option value="2-7">D+2 a D+7</option><option value="8+">D+8 ou mais</option></select><button type="button" onClick={()=>void load()}><RefreshCw size={16}/>Atualizar</button></div>
    {status==='pending'&&canReview&&<div className="confirmation-batch"><label><input type="checkbox" checked={rows.length>0&&selected.size===rows.length} onChange={selectAll}/>Selecionar propostas visíveis</label><span>{selected.size} selecionada{selected.size===1?'':'s'}</span><button type="button" disabled={!selected.size||saving} onClick={()=>void decide([...selected],'approve')}><Check size={16}/>Confirmar selecionadas</button><button type="button" className="reject" disabled={!selected.size||saving} onClick={()=>void decide([...selected],'reject')}><X size={16}/>Rejeitar selecionadas</button></div>}
    {error&&<div className="error">{error}</div>}{loading?<div className="central-loading"><RefreshCw className="spinning"/><span>A calcular e carregar propostas…</span></div>:rows.length===0?<div className="confirmation-empty"><Check size={28}/><strong>Sem movimentos neste filtro</strong><span>As versões técnicas anteriores permanecem preservadas na auditoria.</span></div>:<div className="confirmation-list">{rows.map(proposal=>{const automaticIdtr=isAutomaticIdtr(proposal),isExpanded=expanded.has(proposal.id);return <article key={proposal.id} className={isExpanded?'expanded':''}><div className="confirmation-row">{status==='pending'&&canReview&&<input type="checkbox" checked={selected.has(proposal.id)} onChange={()=>setSelected(current=>{const next=new Set(current);next.has(proposal.id)?next.delete(proposal.id):next.add(proposal.id);return next})}/>}<button type="button" className="confirmation-expand" onClick={()=>toggleDetails(proposal)}>{isExpanded?<ChevronDown/>:<ChevronRight/>}</button><div className="confirmation-rule"><strong>{automaticIdtr?'Par automático · mesmo IDTR':methodLabel(proposal.method)}</strong><span>{proposal.first_accounting_date} a {proposal.last_accounting_date} · D+{proposal.operational_delay}</span></div><div><span>Movimentos</span><strong>{proposal.movement_count.toLocaleString('pt-AO')}</strong></div><div><span>Saldo</span><strong className="balanced">{money(proposal.balance)}</strong></div><span className={`confirmation-status ${proposal.status}`}>{proposal.status==='pending'?'A confirmar':automaticIdtr?'Automática':proposal.status==='approved'?'Confirmada pelo técnico':'Rejeitada'}</span>{status==='pending'&&canReview&&<div className="confirmation-actions"><button title="Confirmar esta proposta" onClick={()=>void decide([proposal.id],'approve')}><Check/></button><button title="Rejeitar esta proposta" className="reject" onClick={()=>void decide([proposal.id],'reject')}><X/></button></div>}</div>{isExpanded&&<div className="confirmation-details"><div className="confirmation-detail-head"><b>{automaticIdtr?'Par reconciliado automaticamente':'Linhas que formam a proposta'}</b><span>{automaticIdtr?'Consulta das duas linhas com o mesmo IDTR e saldo zero.':'A aprovação só é aceite se todas continuarem abertas e a soma continuar em zero.'}</span></div>{details[proposal.id]?.map(movement=><div className="confirmation-movement" key={movement.id}><span>{movement.accounting_date}</span><span className="mono">{movement.operation_number??'—'}</span><span>{movement.raw_description??'—'}</span><strong className={movement.amount>=0?'positive':'negative'}>{money(movement.amount)}</strong><small>{movement.native_idtr?'IDTR '+movement.native_idtr:'Sem IDTR'}</small></div>)??<span>A carregar linhas…</span>}</div>}</article>})}</div>}
  </section>;
}
