import { useEffect, useMemo, useState } from 'react';
import { Activity, RefreshCw } from 'lucide-react';
import { loadAuditLogs, type AuditLog } from './lib/database';

const actionLabels:Record<string,string>={login:'Início de sessão',import_started:'Importação iniciada',import_resumed:'Importação retomada',import_completed:'Importação concluída',v2_import_completed:'Importação Real Time concluída',import_failed:'Importação falhada',export_excel:'Exportação Excel',export_pdf:'Exportação PDF',manual_reconciliation:'Reconciliação manual',user_created:'Utilizador criado',user_updated:'Utilizador atualizado',user_suspended:'Utilizador suspenso',user_reactivated:'Utilizador reativado'};

export default function AuditLogPanel(){
  const [logs,setLogs]=useState<AuditLog[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
  const [actor,setActor]=useState(''),[action,setAction]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState('');
  const refresh=async()=>{setLoading(true);setError('');try{setLogs(await loadAuditLogs());}catch(cause){setError(cause instanceof Error?cause.message:'Não foi possível carregar o log central.');}finally{setLoading(false);}};
  useEffect(()=>{void refresh();},[]);
  const actors=useMemo(()=>[...new Set(logs.map(log=>log.actor))].sort((a,b)=>a.localeCompare(b,'pt')),[logs]);
  const actions=useMemo(()=>[...new Set(logs.map(log=>log.action))].sort(),[logs]);
  const filtered=useMemo(()=>logs.filter(log=>{const date=log.createdAt.slice(0,10);return(!actor||log.actor===actor)&&(!action||log.action===action)&&(!from||date>=from)&&(!to||date<=to);}),[logs,actor,action,from,to]);
  return <section className="panel audit-log-panel"><div className="panel-head"><div><p className="eyebrow">REGISTO CENTRAL</p><h2>Log de utilização</h2><p>Ações efetivamente registadas no Supabase.</p></div><button className="secondary-button" disabled={loading} onClick={()=>void refresh()}><RefreshCw size={16} className={loading?'spinning':''}/>Atualizar</button></div><div className="audit-filters"><label>Utilizador<select value={actor} onChange={event=>setActor(event.target.value)}><option value="">Todos</option>{actors.map(value=><option key={value}>{value}</option>)}</select></label><label>Ação<select value={action} onChange={event=>setAction(event.target.value)}><option value="">Todas</option>{actions.map(value=><option key={value} value={value}>{actionLabels[value]??value}</option>)}</select></label><label>Desde<input type="date" value={from} onChange={event=>setFrom(event.target.value)}/></label><label>Até<input type="date" value={to} onChange={event=>setTo(event.target.value)}/></label><button type="button" onClick={()=>{setActor('');setAction('');setFrom('');setTo('');}}>Limpar filtros</button></div>{error&&<div className="error-box">{error}</div>}{loading?<div className="empty-state"><Activity className="spinning"/><p>A carregar o log central…</p></div>:<><p className="active-filter-note"><strong>{filtered.length.toLocaleString('pt-AO')}</strong> registos encontrados.</p><div className="table-wrap"><table><thead><tr><th>Utilizador</th><th>Ação</th><th>Data e hora</th><th>Informação</th></tr></thead><tbody>{filtered.map(log=><tr key={log.id}><td><strong>{log.actor}</strong>{log.email&&<small>{log.email}</small>}</td><td><span className="badge automatic">{actionLabels[log.action]??log.action}</span></td><td>{new Intl.DateTimeFormat('pt-AO',{dateStyle:'short',timeStyle:'medium'}).format(new Date(log.createdAt))}</td><td>{String(log.details.filename??(log.details.rows?`${Number(log.details.rows).toLocaleString('pt-AO')} linhas`:log.entityType==='session'?'Acesso à plataforma':'—'))}</td></tr>)}</tbody></table>{!filtered.length&&<div className="no-filter-results">Nenhum registo corresponde aos filtros.</div>}</div></>}</section>;
}
