import { useMemo } from 'react';
import { Activity, AlertTriangle, BarChart3, CalendarDays, CheckCircle2, Files, TrendingUp } from 'lucide-react';
import { currentHistory, loadHistory } from './lib/history';

const labels: Record<string,string> = { pos:'POS', atm:'ATM', transfer:'Transferências', commission:'Comissões', service:'Serviços', other:'Outros' };
const coordinates = (values:number[], max:number, width=800, height=170) => values.map((value,index) => [values.length === 1 ? width/2 : index*(width/(values.length-1)),height-(value/Math.max(1,max))*height] as const);
const smoothPath = (coords:readonly (readonly [number,number])[]) => coords.length ? coords.slice(1).reduce((path,[x,y],index)=>{const [px,py]=coords[index],mid=(px+x)/2;return `${path} C ${mid} ${py}, ${mid} ${y}, ${x} ${y}`;},`M ${coords[0][0]} ${coords[0][1]}`) : '';

export default function HistoryDashboard({ revision }: { revision: number }) {
  const all = useMemo(() => loadHistory(), [revision]); const days = currentHistory(all); const latest = days.at(-1);
  if (!latest) return <section className="panel empty-state"><Files size={28}/><h2>Ainda não existem análises guardadas</h2><p>O primeiro extrato concluído iniciará a série diária.</p></section>;
  const dailyMap=new Map<string,{movements:number;automatic:number;unreconciled:number;missingIdtr:number;amount:number}>();
  for(const snapshot of days) for(const [date,value] of Object.entries(snapshot.dailyMetrics??{})) dailyMap.set(date,value);
  const chartDays=[...dailyMap.entries()].sort(([a],[b])=>a.localeCompare(b));
  const dailyValues=chartDays.map(([,value])=>value),totalDaily=dailyValues.reduce((sum,value)=>sum+value.movements,0),automaticDaily=dailyValues.reduce((sum,value)=>sum+value.automatic,0);
  const averageDaily=chartDays.length?totalDaily/chartDays.length:0,maxDaily=Math.max(0,...dailyValues.map(value=>value.movements));
  const lastDaily=dailyValues.at(-1),previousDaily=dailyValues.at(-2),dailyChange=previousDaily?.movements?((lastDaily?.movements??0)-previousDaily.movements)/previousDaily.movements*100:0;
  const alerts=Math.abs(dailyChange)>=30?1:0,chartMax=Math.max(1,...dailyValues.map(value=>value.movements));
  const totalCoords=coordinates(dailyValues.map(value=>value.movements),chartMax),automaticCoords=coordinates(dailyValues.map(value=>value.automatic),chartMax);
  const areaPath=totalCoords.length?`M ${totalCoords[0][0]} 170 L ${totalCoords[0][0]} ${totalCoords[0][1]} ${smoothPath(totalCoords).replace(/^M [^C]+/,'')} L ${totalCoords.at(-1)?.[0]} 170 Z`:'';
  return <div className="history-page">
    <section className="history-kpis expanded"><article><CalendarDays/><span>Dias com dados</span><strong>{chartDays.length}</strong></article><article><Activity/><span>Total processado</span><strong>{totalDaily.toLocaleString('pt-AO')}</strong></article><article><BarChart3/><span>Média diária</span><strong>{Math.round(averageDaily).toLocaleString('pt-AO')}</strong></article><article><TrendingUp/><span>Maior dia</span><strong>{maxDaily.toLocaleString('pt-AO')}</strong></article><article><CheckCircle2/><span>Reconciliação diária</span><strong>{totalDaily?(automaticDaily/totalDaily*100).toFixed(1):'0.0'}%</strong></article><article className={alerts?'alert':''}><AlertTriangle/><span>Variação último dia</span><strong>{dailyChange>=0?'+':''}{dailyChange.toFixed(1)}%</strong></article></section>
    {chartDays.length?<section className="history-chart panel smooth-chart"><div className="panel-head"><div><h2>Evolução diária suavizada</h2><p>Total processado e movimentos em grupos IDTR reconciliados, por <code>MRDATL</code></p></div></div><svg viewBox="0 0 800 210" role="img" aria-label="Curvas da evolução diária dos movimentos"><defs><linearGradient id="keveArea" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#3c19d7" stopOpacity=".22"/><stop offset="1" stopColor="#3c19d7" stopOpacity="0"/></linearGradient></defs><path className="daily-area" d={areaPath}/><path className="total-line" d={smoothPath(totalCoords)}/><path className="automatic-line" d={smoothPath(automaticCoords)}/>{totalCoords.map(([x,y],index)=><circle className="daily-point" key={chartDays[index][0]} cx={x} cy={y} r="3"/>)}{chartDays.map(([date],index)=><text key={date} x={chartDays.length===1?400:index*(800/(chartDays.length-1))} y="202" textAnchor={index===0?'start':index===chartDays.length-1?'end':'middle'}>{date.slice(5)}</text>)}</svg><div className="history-legend"><span className="total">Total diário</span><span className="automatic">Reconciliados por IDTR</span></div></section>:<section className="anomaly-alert"><CalendarDays/><div><strong>Dados diários ainda não calculados</strong><p>As importações existentes são anteriores à agregação diária. Reimporte os extratos para gerar um ponto real por cada MRDATL.</p></div></section>}
    {alerts>0&&<section className="anomaly-alert"><AlertTriangle/><div><strong>Variação diária fora do habitual</strong><p>O volume total do último dia variou {dailyChange.toFixed(1)}% face ao dia anterior. Convém validar se o período está completo.</p></div></section>}
    <section className="history-types"><div className="section-heading"><div><p className="eyebrow">ÚLTIMA IMPORTAÇÃO</p><h2>Composição por natureza</h2></div></div><div className="history-type-grid">{Object.entries(labels).map(([key,label])=>{const now=latest.movementTypes[key]?.total??0;return <article key={key}><span>{label}</span><strong>{now.toLocaleString('pt-AO')}</strong><small>movimentos no último extrato</small></article>})}</div></section>
    <section className="panel"><div className="panel-head"><div><h2>Importações e versões</h2><p>As versões substituídas mantêm-se apenas para auditoria</p></div></div><div className="table-wrap"><table><thead><tr><th>Data</th><th>Versão</th><th>Ficheiro</th><th>Carregamentos</th><th>Utilizador</th><th>Estado</th></tr></thead><tbody>{[...all].sort((a,b)=>b.lastUploadedAt.localeCompare(a.lastUploadedAt)).map(item=><tr key={item.id}><td>{item.reportDate}</td><td>v{item.version}</td><td>{item.filename}</td><td>{item.uploadCount}</td><td>{item.uploadedBy}</td><td><span className={`badge ${item.current?'automatic':'unreconciled'}`}>{item.current?'Versão ativa':'Substituída'}</span></td></tr>)}</tbody></table></div></section>
  </div>;
}
