import { useEffect,useMemo,useState } from 'react';
import { Check,Pencil,Plus,RefreshCw,ShieldCheck,UserRoundCheck,UserRoundX,X } from 'lucide-react';
import { supabase } from './lib/supabase';
import { useAuth } from './AuthGate';
type Role='platform_owner'|'client_admin'|'analyst'|'auditor';
type Profile={id:string;email:string;full_name:string;role:Role;is_active:boolean;pin_enabled:boolean;created_at:string};
const roleLabels:Record<Role,string>={platform_owner:'Proprietário da plataforma',client_admin:'Administrador do cliente',analyst:'Analista',auditor:'Auditor'};
async function invoke(body:Record<string,unknown>){const {data,error}=await supabase.functions.invoke('admin-users',{body});if(error)throw error;if(data?.error)throw new Error(String(data.error));return data;}
export default function UserManagement(){
 const identity=useAuth();
 const [users,setUsers]=useState<Profile[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [creating,setCreating]=useState(false),[editing,setEditing]=useState<Profile|null>(null),[name,setName]=useState(''),[email,setEmail]=useState(''),[role,setRole]=useState<Role>('analyst'),[pin,setPin]=useState('');
 const load=async()=>{setLoading(true);setError('');const {data,error:queryError}=await supabase.from('profiles').select('id,email,full_name,role,is_active,pin_enabled,created_at').order('full_name');if(queryError)setError(queryError.message);else setUsers((data??[]) as Profile[]);setLoading(false);};useEffect(()=>{void load();},[]);
 const counts=useMemo(()=>({total:users.length,active:users.filter(x=>x.is_active).length,suspended:users.filter(x=>!x.is_active).length,admins:users.filter(x=>x.role==='client_admin'&&x.is_active).length}),[users]);
 const reset=()=>{setCreating(false);setEditing(null);setName('');setEmail('');setRole('analyst');setPin('');};
 const startEdit=(user:Profile)=>{setCreating(false);setEditing(user);setName(user.full_name);setEmail(user.email);setRole(user.role);setPin('');setError('');setMessage('');};
 const submit=async()=>{setSaving(true);setError('');setMessage('');try{if(creating){await invoke({action:'create',fullName:name,email,role,pin});setMessage('Utilizador criado e pronto para entrar com PIN.');}else if(editing){if(editing.role!=='platform_owner')await invoke({action:'update',userId:editing.id,fullName:name,role});if(pin)await invoke({action:'set_pin',userId:editing.id,pin});setMessage(pin?'Utilizador e PIN atualizados.':'Utilizador atualizado.');}reset();await load();}catch(cause){setError(cause instanceof Error?cause.message:'Não foi possível guardar o utilizador.');}finally{setSaving(false);}};
 const setActive=async(user:Profile)=>{setSaving(true);setError('');setMessage('');try{await invoke({action:'set_active',userId:user.id,isActive:!user.is_active});setMessage(user.is_active?'Conta suspensa e acesso bloqueado.':'Conta reativada.');await load();}catch(cause){setError(cause instanceof Error?cause.message:'Não foi possível alterar a conta.');}finally{setSaving(false);}};
 const formOpen=creating||Boolean(editing);
 return <section className="panel user-management"><div className="panel-head"><div><p className="eyebrow">ADMINISTRAÇÃO</p><h2>Gestão de utilizadores</h2><p>Crie, edite, suspenda ou reative contas. Todas as alterações ficam no log central.</p></div><div className="user-head-actions"><button className="secondary-button" disabled={loading} onClick={()=>void load()}><RefreshCw size={16} className={loading?'spinning':''}/>Atualizar</button><button className="primary-button" onClick={()=>{reset();setCreating(true);}}><Plus size={17}/>Novo utilizador</button></div></div>
 <div className="user-kpis"><article><span>Total visível</span><strong>{counts.total}</strong></article><article className="good"><span>Ativos</span><strong>{counts.active}</strong></article><article className="warn"><span>Suspensos</span><strong>{counts.suspended}</strong></article><article><span>Administradores do cliente</span><strong>{counts.admins}</strong></article></div>
 {formOpen&&<div className="user-form"><div className="user-form-title"><div><ShieldCheck size={20}/><strong>{creating?'Criar utilizador':editing?.role==='platform_owner'?'Definir o meu PIN':'Editar utilizador'}</strong></div><button aria-label="Fechar" onClick={reset}><X size={18}/></button></div><div className="user-form-grid"><label>Nome completo<input disabled={editing?.role==='platform_owner'} value={name} onChange={e=>setName(e.target.value)} placeholder="Nome e apelido"/></label><label>Email<input type="email" disabled={Boolean(editing)} value={email} onChange={e=>setEmail(e.target.value)} placeholder="utilizador@empresa.com"/></label><label>Perfil<select value={role} disabled={editing?.role==='platform_owner'} onChange={e=>setRole(e.target.value as Role)}><option value="analyst">Analista</option><option value="auditor">Auditor</option><option value="client_admin">Administrador do cliente</option>{editing?.role==='platform_owner'&&<option value="platform_owner">Proprietário da plataforma</option>}</select></label><label>{creating?'PIN de acesso':'Novo PIN (opcional)'}<input className="pin-input" type="password" inputMode="numeric" pattern="[0-9]{4}" maxLength={4} value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,'').slice(0,4))} placeholder="4 algarismos"/><small>Exatamente 4 algarismos. Nunca fica visível nem guardado em texto.</small></label></div><div className="user-form-actions"><button onClick={reset}>Cancelar</button><button className="primary-button" disabled={saving||!name.trim()||!email.trim()||(creating&&pin.length!==4)||(Boolean(editing)&&Boolean(pin)&&pin.length!==4)||(editing?.role==='platform_owner'&&pin.length!==4)} onClick={()=>void submit()}><Check size={17}/>{saving?'A guardar…':'Guardar'}</button></div></div>}
 {error&&<div className="error-box">{error}</div>}{message&&<div className="success-box">{message}</div>}
 <div className="table-wrap"><table><thead><tr><th>Utilizador</th><th>Perfil</th><th>Estado</th><th>PIN</th><th>Criado em</th><th>Ações</th></tr></thead><tbody>{users.map(user=><tr key={user.id}><td><strong>{user.full_name||'Sem nome'}</strong><small>{user.email}</small></td><td><span className="badge automatic">{roleLabels[user.role]}</span></td><td><span className={`user-status ${user.is_active?'active':'suspended'}`}>{user.is_active?<UserRoundCheck size={15}/>:<UserRoundX size={15}/>} {user.is_active?'Ativo':'Suspenso'}</span></td><td><span className={`user-status ${user.pin_enabled?'active':'suspended'}`}>{user.pin_enabled?'Configurado':'Por definir'}</span></td><td>{new Intl.DateTimeFormat('pt-AO',{dateStyle:'short'}).format(new Date(user.created_at))}</td><td>{user.role==='platform_owner'?<div className="user-row-actions"><span className="owner-protected"><ShieldCheck size={15}/>Protegida</span><button onClick={()=>startEdit(user)}><Pencil size={15}/>Definir PIN</button></div>:<div className="user-row-actions"><button onClick={()=>startEdit(user)}><Pencil size={15}/>Editar</button><button className={user.is_active?'danger':'success'} disabled={saving} onClick={()=>void setActive(user)}>{user.is_active?<UserRoundX size={15}/>:<UserRoundCheck size={15}/>} {user.is_active?'Suspender':'Reativar'}</button></div>}</td></tr>)}</tbody></table>{!loading&&!users.length&&<div className="no-filter-results">Nenhum utilizador encontrado.</div>}</div>{!identity.isPlatformOwner&&<p className="permission-note"><ShieldCheck size={15}/>Como Administrador do cliente, pode gerir contas operacionais e outros administradores do cliente. Os logs e a conta do proprietário da plataforma permanecem reservados.</p>}</section>;
}
